apiVersion: v1
kind: Service
metadata:
  name: promexporter
  namespace: default
  labels:
    app: nginx-prometheus-exporter
spec:
  type: ClusterIP
  selector:
    app: nginx-prometheus-exporter
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
